### ISSUE TITLE
Traditional Location Gathering Methods Aren't Supported by Google Chrome W/O SSL

### ISSUE THREAD

**Issue by charlesabarnes** [SpaghettiCodeStudios/HowMuchWithTax#5]
Google Chrome doesn't support obtaining the coordinates without using SSL (HTTPS).   To enable SSL we have a few options.

Free:
- Auto redirect anybody going to http://spaghetticodestudios.github.io/HowMuchWithTax  to https://spaghetticodestudios.github.io/HowMuchWithTax

Paid:
- Begin hosting our own site and use [Lets Encrypt](https://letsencrypt.org/)

Which works best for us?

**Comment by TFilla** [comment]
Redirect for now. We should probably wait to begin hosting until we have a decent sized ball rolling.

**Comment by charlesabarnes** [comment]
Resolved in the aforementioned merge^^
